/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Cloud.glb
Author: RunemarkStudio (https://sketchfab.com/runemarkstudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-cloud-f31be54812a348df86d94171098dae19
Title: Cartoon Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function CloudModel(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/Cloud.glb')
  const mesh =useRef(null);
  useFrame(() => {
    mesh.current.rotation.x = mesh.current.rotation.x += 0.003
  });
  return (
    <group {...props} dispose={null}>
      <mesh ref={mesh} geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Cloud.glb')
